// Package sandbox runs REAL Python/shell code generated by the agent, but inside
// an ephemeral Docker container. The container gets network access but only a
// single scratch working directory is bind-mounted from the host — the rest of
// the host filesystem (SSH keys, system files, this repo) is invisible to the
// code. Resource limits (memory, CPU, PIDs) and a hard timeout bound each run.
//
// This is the honest reconciliation of "let the LLM write and run code" with
// "controlled execution": the model may author arbitrary scripts, but their
// capabilities and blast radius are contained by the container, and every run is
// captured for audit.
package sandbox

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// Spec is one code-execution request.
type Spec struct {
	Lang       string // "python" | "shell"
	Code       string
	TimeoutSec int
}

// Result captures the outcome of a run.
type Result struct {
	Stdout     string `json:"stdout"`
	Stderr     string `json:"stderr"`
	ExitCode   int    `json:"exit_code"`
	TimedOut   bool   `json:"timed_out"`
	DurationMs int64  `json:"duration_ms"`
}

// Config configures the Docker executor.
type Config struct {
	Image          string  // e.g. "python:3.12-slim"
	WorkDirHost    string  // host scratch dir, mounted at /work
	Network        string  // "all" (bridge) or "none"
	MemoryMB       int     // container memory limit
	CPUs           float64 // container CPU limit
	PidsLimit      int     // max processes
	DefaultTimeout int     // seconds
	OutputLimit    int     // max bytes captured per stream
}

// Docker is a container-backed code executor.
type Docker struct {
	cfg     Config
	uidGid  string
	absWork string
}

// NewDocker validates the environment and prepares the scratch directory.
func NewDocker(cfg Config) (*Docker, error) {
	if cfg.Image == "" {
		cfg.Image = "python:3.12-slim"
	}
	if cfg.Network == "" {
		cfg.Network = "all"
	}
	if cfg.MemoryMB == 0 {
		cfg.MemoryMB = 512
	}
	if cfg.CPUs == 0 {
		cfg.CPUs = 1.0
	}
	if cfg.PidsLimit == 0 {
		cfg.PidsLimit = 256
	}
	if cfg.DefaultTimeout == 0 {
		cfg.DefaultTimeout = 30
	}
	if cfg.OutputLimit == 0 {
		cfg.OutputLimit = 16 * 1024
	}
	if cfg.WorkDirHost == "" {
		cfg.WorkDirHost = "sandbox_workspace"
	}
	if _, err := exec.LookPath("docker"); err != nil {
		return nil, fmt.Errorf("sandbox: docker not found in PATH: %w", err)
	}
	abs, err := resolveWorkDir(cfg.WorkDirHost)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(abs, 0o755); err != nil {
		return nil, fmt.Errorf("sandbox: create workdir: %w", err)
	}
	return &Docker{
		cfg:     cfg,
		uidGid:  fmt.Sprintf("%d:%d", os.Getuid(), os.Getgid()),
		absWork: abs,
	}, nil
}

// WorkDir returns the absolute host scratch directory.
func (d *Docker) WorkDir() string { return d.absWork }

// resolveWorkDir places the scratch dir somewhere the container runtime can
// bind-mount. Some runtimes (e.g. Colima) only share the user's HOME, so any
// relative or "~" path is anchored under $HOME/.liveagent to guarantee the mount
// actually works.
func resolveWorkDir(p string) (string, error) {
	home, _ := os.UserHomeDir()
	if p == "" {
		p = "sandbox"
	}
	if strings.HasPrefix(p, "~/") && home != "" {
		p = filepath.Join(home, p[2:])
	}
	if !filepath.IsAbs(p) && home != "" {
		p = filepath.Join(home, ".liveagent", p)
	}
	return filepath.Abs(p)
}

// Run executes the spec's code inside a fresh container and returns its output.
func (d *Docker) Run(ctx context.Context, spec Spec) (Result, error) {
	timeout := spec.TimeoutSec
	if timeout <= 0 {
		timeout = d.cfg.DefaultTimeout
	}

	// Write the script into the scratch dir so it appears at /work in the container.
	var fname, interp string
	switch spec.Lang {
	case "shell", "sh", "bash":
		fname = fmt.Sprintf(".run_%d.sh", time.Now().UnixNano())
		interp = "sh"
	default: // python
		fname = fmt.Sprintf(".run_%d.py", time.Now().UnixNano())
		interp = "python"
	}
	scriptPath := filepath.Join(d.absWork, fname)
	if err := os.WriteFile(scriptPath, []byte(spec.Code), 0o644); err != nil {
		return Result{}, fmt.Errorf("sandbox: write script: %w", err)
	}
	defer os.Remove(scriptPath)

	network := "bridge"
	if d.cfg.Network == "none" {
		network = "none"
	}

	args := []string{
		"run", "--rm",
		"--network", network,
		"--memory", strconv.Itoa(d.cfg.MemoryMB) + "m",
		"--cpus", strconv.FormatFloat(d.cfg.CPUs, 'f', -1, 64),
		"--pids-limit", strconv.Itoa(d.cfg.PidsLimit),
		"--user", d.uidGid,
		"-v", d.absWork + ":/work",
		"-w", "/work",
		d.cfg.Image,
		// `timeout` (coreutils) enforces the wall-clock limit inside the container.
		"timeout", "--signal=KILL", strconv.Itoa(timeout), interp, "/work/" + fname,
	}

	// Outer deadline guards against a hung docker CLI itself.
	runCtx, cancel := context.WithTimeout(ctx, time.Duration(timeout+15)*time.Second)
	defer cancel()

	start := time.Now()
	cmd := exec.CommandContext(runCtx, "docker", args...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	dur := time.Since(start).Milliseconds()

	res := Result{
		Stdout:     truncate(stdout.String(), d.cfg.OutputLimit),
		Stderr:     truncate(stderr.String(), d.cfg.OutputLimit),
		DurationMs: dur,
	}
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			res.ExitCode = exitErr.ExitCode()
			// `timeout` returns 124 (or 137 when KILL) on timeout.
			if res.ExitCode == 124 || res.ExitCode == 137 {
				res.TimedOut = true
			}
			return res, nil
		}
		return res, fmt.Errorf("sandbox: docker run: %w", err)
	}
	return res, nil
}

func truncate(s string, n int) string {
	if n <= 0 || len(s) <= n {
		return s
	}
	return s[:n] + "\n...[truncated]"
}
